<?php

namespace Proxies\__CG__\Adonai\UnicoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Estudiantes extends \Adonai\UnicoBundle\Entity\Estudiantes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'idEst', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'nuip', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'nomEst', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'fechaNac', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'tel', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'dir', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'acudiente');
        }

        return array('__isInitialized__', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'idEst', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'nuip', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'nomEst', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'fechaNac', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'tel', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'dir', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Estudiantes' . "\0" . 'acudiente');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Estudiantes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdEst()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdEst();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEst', array());

        return parent::getIdEst();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuip($nuip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuip', array($nuip));

        return parent::setNuip($nuip);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuip', array());

        return parent::getNuip();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomEst($nomEst)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomEst', array($nomEst));

        return parent::setNomEst($nomEst);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomEst()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomEst', array());

        return parent::getNomEst();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNac($fechaNac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNac', array($fechaNac));

        return parent::setFechaNac($fechaNac);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNac', array());

        return parent::getFechaNac();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', array($tel));

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', array());

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setDir($dir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDir', array($dir));

        return parent::setDir($dir);
    }

    /**
     * {@inheritDoc}
     */
    public function getDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDir', array());

        return parent::getDir();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcudiente(\Adonai\UnicoBundle\Entity\Acudientes $acudiente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcudiente', array($acudiente));

        return parent::setAcudiente($acudiente);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcudiente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcudiente', array());

        return parent::getAcudiente();
    }

}
