<?php

namespace Adonai\UnicoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocentesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocentesRepository extends EntityRepository
{
	
}
