adonai_unico:
    resource: "@AdonaiUnicoBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

AdonaiUsuarios_admin:
    path:  /admin_panel
    defaults: { _controller: AdonaiUnicoBundle:Default:admin }

AdonaiUsuarios_docente:
    path:  /docente_panel
    defaults: { _controller: AdonaiUnicoBundle:Default:docente }

AdonaiUsuarios_inicio:
    path:  /index
    defaults: { _controller: AdonaiUnicoBundle:Default:index }

login:
    path: /login
    defaults: { _controller: AdonaiUnicoBundle:Security:login }

login_check:
    path: /login_check
    defaults: { _controller: AdonaiUnicoBundle:Default:admin }

logout:
    path: /logout

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

select_matriculas:
    pattern:  /matriculas_select
    defaults: { _controller: AdonaiUnicoBundle:Matriculas:matriculasSelect }
    options:
        expose: true   

select_competencias:
    pattern:  /competencias_select
    defaults: { _controller: AdonaiUnicoBundle:Competencias:competenciasSelect }
    options:
        expose: true

notas_edit:
    pattern:  /notas/edit
    defaults: { _controller: AdonaiUnicoBundle:Notas:edit }
    options:
        expose: true

nota_existente:
    pattern:  /nota_existente
    defaults: { _controller: AdonaiUnicoBundle:Notas:notasExistentes }
    options:
        expose: true

comprobar_registros:
    pattern:  /comprobar_registros
    defaults: { _controller: AdonaiUnicoBundle:Notas:comprobarRegistros }
    options:
        expose: true

todas_notas:
    pattern:  /todas_notas
    defaults: { _controller: AdonaiUnicoBundle:Notas:devolverTodasNotas }
    options:
        expose: true 