security:
    encoders:
        Adonai\UnicoBundle\Entity\Usuarios:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: AdonaiUnicoBundle:Usuarios, property: username }

    firewalls:
        admin_area:
            pattern:    /.*
            provider: administrators
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true
    access_control:
        - { path: ^/admin_panel, roles: ROLE_ADMIN }
        - { path: ^/docente_panel, roles: ROLE_DOCENTE }