<?php

namespace Proxies\__CG__\Adonai\UnicoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Periodos extends \Adonai\UnicoBundle\Entity\Periodos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Periodos' . "\0" . 'idPeriodo', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Periodos' . "\0" . 'fechaInPer', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Periodos' . "\0" . 'fechaFinPer', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Periodos' . "\0" . 'numero', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Periodos' . "\0" . 'a_lectivo');
        }

        return array('__isInitialized__', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Periodos' . "\0" . 'idPeriodo', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Periodos' . "\0" . 'fechaInPer', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Periodos' . "\0" . 'fechaFinPer', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Periodos' . "\0" . 'numero', '' . "\0" . 'Adonai\\UnicoBundle\\Entity\\Periodos' . "\0" . 'a_lectivo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Periodos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPeriodo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPeriodo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPeriodo', array());

        return parent::getIdPeriodo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaInPer($fechaInPer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaInPer', array($fechaInPer));

        return parent::setFechaInPer($fechaInPer);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInPer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInPer', array());

        return parent::getFechaInPer();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInPerDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInPerDate', array());

        return parent::getFechaInPerDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFinPer($fechaFinPer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFinPer', array($fechaFinPer));

        return parent::setFechaFinPer($fechaFinPer);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFinPer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFinPer', array());

        return parent::getFechaFinPer();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFinPerDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFinPerDate', array());

        return parent::getFechaFinPerDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', array($numero));

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', array());

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setALectivo(\Adonai\UnicoBundle\Entity\ALectivos $a_lectivo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setALectivo', array($a_lectivo));

        return parent::setALectivo($a_lectivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getALectivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getALectivo', array());

        return parent::getALectivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodoActual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodoActual', array());

        return parent::getPeriodoActual();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodosActuales($al_actual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodosActuales', array($al_actual));

        return parent::getPeriodosActuales($al_actual);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
